version: "2"

run:
  concurrency: 4
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: type name will be used as monitor.MonitorOption

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/hypnoglow/go-pg-monitor)
    goimports:
      local-prefixes: github.com/hypnoglow/go-pg-monitor

issues:
  fix: true
