{
 "title": "Postgres Database Client",
 "tags": [
  "postgres",
  "database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   { "name": "period", "label": "Period", "query": "1m,5m,10m,1h" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(go_pg_pool_total_connections{}, kubernetes_namespace)"
    }
   },
   {
    "name": "app_instance",
    "label": "App Instance",
    "query": {
     "query": "label_values(go_pg_pool_total_connections{kubernetes_namespace=\"$namespace\"}, app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_pg_pool_total_connections{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$app_instance\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(go_pg_pool_idle_connections{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$app_instance\"})",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Pool Connections Reaped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(go_pg_pool_stale_connections{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$app_instance\"}[$period]))",
     "legendFormat": "stale"
    }
   ]
  },
  {
   "title": "Pool Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(go_pg_pool_hits{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$app_instance\"}[$period]))",
     "legendFormat": "hits"
    }
   ]
  },
  {
   "title": "Pool Misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(go_pg_pool_misses{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$app_instance\"}[$period]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Pool Timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(go_pg_pool_timeouts{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$app_instance\"}[$period]))",
     "legendFormat": "timeouts"
    }
   ]
  }
 ]
}